version: '3.6'

services:
  mysql80:
    image: mysql:8.0
    container_name: mysql80
    hostname: mysql-8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ~/docker-tmp/mysql80:/var/lib/mysql
      - ~/docker-tmp/mysql80-log:/var/log/mysql
    command: ["mysqld", "--server_id=1","--log_bin"]
    ports:
      - "3606:3306"
